## This is the first notebook ,of the series that i am going to creat on the udemy toutorial.Hopefully,I will later create my own library taking help from these codes.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
#This block is only for google colab

from google.colab import files

uploaded = files.upload()

Saving Data.csv to Data.csv


In [ ]:
#Importing the dataset


dataset = pd.read_csv('Data.csv')       #dataset is of type DataFrame

x = dataset.iloc[:,:-1].values           #using .values generates array
y = dataset.iloc[:,-1].values             #x & y is of type np.ndarray


In [ ]:
#Taking care of missing values

from sklearn.impute import SimpleImputer

imputer = SimpleImputer( missing_values = np.nan , strategy = "mean")      #axis=0 for mean along the column
#print(x)
imputer = imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
#print(x)

In [ ]:
#Encoding categorical data

from sklearn.preprocessing import LabelEncoder , OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_x = LabelEncoder()                                                 #the categorical data (country & label here) will be  
x[:,0] = labelencoder_x.fit_transform(x[:,0])                                   #transformed into labels(0,1,2.....)
#print(x)

columntransformer = ColumnTransformer([('town', OneHotEncoder() , [0])] , remainder = "passthrough")            #but if some countries are labeled with higher values
x = columntransformer.fit_transform(x)                                                                          #that can be misleading, so we transform them to one-hot vectors.
print(x)

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
#print(y)



[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
#Splitting the dataset into Training set and Test set

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(x,y, test_size = 0.2 , random_state = 0)
print(X_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

print(X_train)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
